// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace ECS_login_CodedUITest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// ECS_login_RecordedMethod1 - Use 'ECS_login_RecordedMethod1Params' to pass parameters into this method.
        /// </summary>
        public void ECS_login_RecordedMethod1()
        {
            #region Variable Declarations
            HtmlEdit uIUserNameEdit = this.UIECSPortalSacramentoSWindow.UIECSPortalSacramentoSDocument1.UIUserNameEdit;
            HtmlEdit uIPasswordEdit = this.UIECSPortalSacramentoSWindow.UIECSPortalSacramentoSDocument1.UIPasswordEdit;
            HtmlInputButton uILoginButton = this.UIECSPortalSacramentoSWindow.UIECSPortalSacramentoSDocument1.UILoginButton;
            #endregion

            // Last mouse action was not recorded.

            // Type 'palaniss' in 'User Name :' text box
            uIUserNameEdit.Text = this.ECS_login_RecordedMethod1Params.UIUserNameEditText;

            // Type '{Tab}' in 'User Name :' text box
            Keyboard.SendKeys(uIUserNameEdit, this.ECS_login_RecordedMethod1Params.UIUserNameEditSendKeys, ModifierKeys.None);

            // Type '********' in 'Password :' text box
            uIPasswordEdit.Password = this.ECS_login_RecordedMethod1Params.UIPasswordEditPassword;

            // Type '{Tab}' in 'Password :' text box
            Keyboard.SendKeys(uIPasswordEdit, this.ECS_login_RecordedMethod1Params.UIPasswordEditSendKeys, ModifierKeys.None);

            // Type '{Enter}' in 'Login >>' button
            Keyboard.SendKeys(uILoginButton, this.ECS_login_RecordedMethod1Params.UILoginButtonSendKeys, ModifierKeys.None);
        }
        
        #region Properties
        public virtual ECS_login_RecordedMethod1Params ECS_login_RecordedMethod1Params
        {
            get
            {
                if ((this.mECS_login_RecordedMethod1Params == null))
                {
                    this.mECS_login_RecordedMethod1Params = new ECS_login_RecordedMethod1Params();
                }
                return this.mECS_login_RecordedMethod1Params;
            }
        }
        
        public UIECSPortalSacramentoSWindow UIECSPortalSacramentoSWindow
        {
            get
            {
                if ((this.mUIECSPortalSacramentoSWindow == null))
                {
                    this.mUIECSPortalSacramentoSWindow = new UIECSPortalSacramentoSWindow();
                }
                return this.mUIECSPortalSacramentoSWindow;
            }
        }
        #endregion
        
        #region Fields
        private ECS_login_RecordedMethod1Params mECS_login_RecordedMethod1Params;
        
        private UIECSPortalSacramentoSWindow mUIECSPortalSacramentoSWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'ECS_login_RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class ECS_login_RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'palaniss' in 'User Name :' text box
        /// </summary>
        public string UIUserNameEditText = "palaniss";
        
        /// <summary>
        /// Type '{Tab}' in 'User Name :' text box
        /// </summary>
        public string UIUserNameEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'Password :' text box
        /// </summary>
        public string UIPasswordEditPassword = "JXdO6tvPW+7o30wLvqyvXsX3hwJFg32eV0AxwV2UfcA=";
        
        /// <summary>
        /// Type '{Tab}' in 'Password :' text box
        /// </summary>
        public string UIPasswordEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '{Enter}' in 'Login >>' button
        /// </summary>
        public string UILoginButtonSendKeys = "{Enter}";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIECSPortalSacramentoSWindow : BrowserWindow
    {
        
        public UIECSPortalSacramentoSWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "ECS Portal | Sacramento State | College of Engineering & Computer Science | Sacra" +
                "mento State";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("ECS Portal | Sacramento State | College of Engineering & Computer Science | Sacra" +
                    "mento State");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIECSPortalSacramentoSDocument1 UIECSPortalSacramentoSDocument1
        {
            get
            {
                if ((this.mUIECSPortalSacramentoSDocument1 == null))
                {
                    this.mUIECSPortalSacramentoSDocument1 = new UIECSPortalSacramentoSDocument1(this);
                }
                return this.mUIECSPortalSacramentoSDocument1;
            }
        }
        #endregion
        
        #region Fields
        private UIECSPortalSacramentoSDocument1 mUIECSPortalSacramentoSDocument1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIECSPortalSacramentoSDocument1 : HtmlDocument
    {
        
        public UIECSPortalSacramentoSDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "ECS Portal | Sacramento State | College of Engineering & Computer Science | Sacra" +
                "mento State";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/index.php";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://www.ecs.csus.edu/index.php?content=ecs_portal";
            this.WindowTitles.Add("ECS Portal | Sacramento State | College of Engineering & Computer Science | Sacra" +
                    "mento State");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIUserNameEdit
        {
            get
            {
                if ((this.mUIUserNameEdit == null))
                {
                    this.mUIUserNameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIUserNameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "username";
                    this.mUIUserNameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "username";
                    this.mUIUserNameEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "User Name : ";
                    this.mUIUserNameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIUserNameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIUserNameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUIUserNameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"username\" id=\"username\"";
                    this.mUIUserNameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "3";
                    this.mUIUserNameEdit.WindowTitles.Add("ECS Portal | Sacramento State | College of Engineering & Computer Science | Sacra" +
                            "mento State");
                    #endregion
                }
                return this.mUIUserNameEdit;
            }
        }
        
        public HtmlEdit UIPasswordEdit
        {
            get
            {
                if ((this.mUIPasswordEdit == null))
                {
                    this.mUIPasswordEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "passwd";
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "passwd";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Password :";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"passwd\" id=\"passwd\" type=\"password";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "4";
                    this.mUIPasswordEdit.WindowTitles.Add("ECS Portal | Sacramento State | College of Engineering & Computer Science | Sacra" +
                            "mento State");
                    #endregion
                }
                return this.mUIPasswordEdit;
            }
        }
        
        public HtmlInputButton UILoginButton
        {
            get
            {
                if ((this.mUILoginButton == null))
                {
                    this.mUILoginButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUILoginButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUILoginButton.SearchProperties[HtmlButton.PropertyNames.Name] = "/portal_login";
                    this.mUILoginButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Login >>";
                    this.mUILoginButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUILoginButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUILoginButton.FilterProperties[HtmlButton.PropertyNames.Class] = null;
                    this.mUILoginButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "name=\"/portal_login\" type=\"submit\" value";
                    this.mUILoginButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "5";
                    this.mUILoginButton.WindowTitles.Add("ECS Portal | Sacramento State | College of Engineering & Computer Science | Sacra" +
                            "mento State");
                    #endregion
                }
                return this.mUILoginButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIUserNameEdit;
        
        private HtmlEdit mUIPasswordEdit;
        
        private HtmlInputButton mUILoginButton;
        #endregion
    }
}
